### ISSUE TITLE
npm 3 support

### ISSUE THREAD

**Issue by jswhisperer** [hugs/node-castro#3]
I believe it is an updated npm issue.

```
castro$ npm install castro
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine castro@0.0.2: wanted: {"node":">= 0.6.0 && < 0.11.0"} (current: {"node":"4.2.1","npm":"3.5.3"})
npm WARN deprecated NodObjC@1.0.0: The npm registry can, sadly, no longer handle package names with uppercase characters… You must use the 'nodobjc' package now.

> ref@0.3.5 install /Users/greg/Sites3/castro/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:8:
In file included from ../../nan/nan.h:74:
In file included from ../../nan/nan_new.h:181:
../../nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/greg/.node-gyp/4.2.1/include/node/v8.h:4675:3: note: 'New' declared here
  static Local<Signature> New(
  ^
In file included from ../src/binding.cc:8:
../../nan/nan.h:165:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:160:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:253:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:258:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:263:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:268:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:500:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:511:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/greg/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/greg/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/greg/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/greg/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/binding.cc:8:
../../nan/nan.h:515:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/greg/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/greg/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/greg/.node-gyp/4.2.1/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/greg/.node-gyp/4.2.1/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/binding.cc:8:
../../nan/nan.h:522:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../../nan/nan.h:1339:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:1354:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(node::MakeCallback(
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:1427:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../src/binding.cc:154:23: error: no matching function for call to 'NanNewBufferHandle'
  Local<Object> buf = NanNewBufferHandle(ptr, buf_size, unref_null_cb, user_data);
                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:497:36: note: candidate function not viable: no known conversion from 'void (char *, void *)' to 'int' for 3rd argument
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:507:36: note: candidate function not viable: requires 2 arguments, but 4 were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:514:36: note: candidate function not viable: requires single argument 'size', but 4 arguments were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                   ^
../src/binding.cc:271:27: error: no matching function for call to 'NanNewBufferHandle'
  Local<Object> rtn_buf = NanNewBufferHandle(val, size, read_pointer_cb, user_data);
                          ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:497:36: note: candidate function not viable: no known conversion from 'void (char *, void *)' to 'int' for 3rd argument
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:507:36: note: candidate function not viable: requires 2 arguments, but 4 were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:514:36: note: candidate function not viable: requires single argument 'size', but 4 arguments were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                   ^
../src/binding.cc:518:23: error: no matching function for call to 'NanNewBufferHandle'
  Local<Object> rtn = NanNewBufferHandle(ptr, size, read_pointer_cb, NULL);
                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:497:36: note: candidate function not viable: no known conversion from 'void (char *, void *)' to 'int' for 3rd argument
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:507:36: note: candidate function not viable: requires 2 arguments, but 4 were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:514:36: note: candidate function not viable: requires single argument 'size', but 4 arguments were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                   ^
../src/binding.cc:565:23: error: no matching function for call to 'NanNewBufferHandle'
  Local<Object> rtn = NanNewBufferHandle(ptr, size, read_pointer_cb, NULL);
                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:497:36: note: candidate function not viable: no known conversion from 'void (char *, void *)' to 'int' for 3rd argument
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:507:36: note: candidate function not viable: requires 2 arguments, but 4 were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../../nan/nan.h:514:36: note: candidate function not viable: requires single argument 'size', but 4 arguments were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                   ^
17 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/greg/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/greg/.nvm/versions/node/v4.2.1/bin/node" "/Users/greg/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/greg/Sites3/castro/node_modules/ref
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/Users/greg/Sites3/castro
├── bindings@1.2.1 
└─┬ debug@2.2.0 
  └── ms@0.7.1 

npm WARN enoent ENOENT: no such file or directory, open '/Users/greg/Sites3/castro/package.json'
npm WARN castro No description
npm WARN castro No repository field.
npm WARN castro No README data
npm WARN castro No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/greg/.nvm/versions/node/v4.2.1/bin/node" "/Users/greg/.nvm/versions/node/v4.2.1/bin/npm" "install" "castro"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! ref@0.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@0.3.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/greg/Sites3/castro/npm-debug.log
```

**Comment by hugs** [comment]
The issue is now quite old and probably not a problem anymore. Looks like the error you saw was because Castro was requiring an old and incompatible version of NodObjC. I fixed this by publishing a new version of Castro (0.3) that works with the latest version of nodobjc. (The case-sensitive "nodobjc" is now the new official npm package name for NodObjC.) 

Castro 0.3 was tested with Node v4.5.0 on OS X El Capitan 10.11.6.

If you're still seeing this error, though, let me know.
